//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSecurity.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSecurity.Languages.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Nuevo.
        /// </summary>
        internal static string GEN001_Btn001 {
            get {
                return ResourceManager.GetString("GEN001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Modificar.
        /// </summary>
        internal static string GEN001_Btn002 {
            get {
                return ResourceManager.GetString("GEN001_Btn002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Eliminar.
        /// </summary>
        internal static string GEN001_Btn003 {
            get {
                return ResourceManager.GetString("GEN001_Btn003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cerrar.
        /// </summary>
        internal static string GEN001_Btn004 {
            get {
                return ResourceManager.GetString("GEN001_Btn004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Buscar.
        /// </summary>
        internal static string GEN001_Btn005 {
            get {
                return ResourceManager.GetString("GEN001_Btn005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        internal static string GEN001_Btn006 {
            get {
                return ResourceManager.GetString("GEN001_Btn006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ca&amp;ncelar.
        /// </summary>
        internal static string GEN001_Btn007 {
            get {
                return ResourceManager.GetString("GEN001_Btn007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es obligatorio.
        /// </summary>
        internal static string GEN001_Val001 {
            get {
                return ResourceManager.GetString("GEN001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ingresado no es numérico.
        /// </summary>
        internal static string GEN001_Val002 {
            get {
                return ResourceManager.GetString("GEN001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cancelar.
        /// </summary>
        internal static string Login_BtnCancel {
            get {
                return ResourceManager.GetString("Login_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        internal static string Login_BtnOk {
            get {
                return ResourceManager.GetString("Login_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string Login_LblPass {
            get {
                return ResourceManager.GetString("Login_LblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario:.
        /// </summary>
        internal static string Login_LblUser {
            get {
                return ResourceManager.GetString("Login_LblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña inválidos.
        /// </summary>
        internal static string Login_Msg001 {
            get {
                return ResourceManager.GetString("Login_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe completar los campos usuario y contraseña.
        /// </summary>
        internal static string Login_Msg002 {
            get {
                return ResourceManager.GetString("Login_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Principal &quot;Gabe&quot;.
        /// </summary>
        internal static string MDI_Gabe {
            get {
                return ResourceManager.GetString("MDI_Gabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string MDI_Gabe_Mnu001 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string MDI_Gabe_Mnu002 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string MDI_Gabe_Mnu005 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cerrar.
        /// </summary>
        internal static string Splash_BtnCancel {
            get {
                return ResourceManager.GetString("Splash_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicializando....
        /// </summary>
        internal static string Splash001_Msg000 {
            get {
                return ResourceManager.GetString("Splash001_Msg000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando actualizaciones....
        /// </summary>
        internal static string Splash001_Msg001 {
            get {
                return ResourceManager.GetString("Splash001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectandose a la base de datos....
        /// </summary>
        internal static string Splash001_Msg002 {
            get {
                return ResourceManager.GetString("Splash001_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificando integridad del sistema....
        /// </summary>
        internal static string Splash001_Msg003 {
            get {
                return ResourceManager.GetString("Splash001_Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando aplicación....
        /// </summary>
        internal static string Splash001_Msg004 {
            get {
                return ResourceManager.GetString("Splash001_Msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Verificación de integridad, consulte al Administrador del Sistema.
        /// </summary>
        internal static string Splash001_MsgBox001 {
            get {
                return ResourceManager.GetString("Splash001_MsgBox001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mod. &amp;Idioma.
        /// </summary>
        internal static string USR001_Btn001 {
            get {
                return ResourceManager.GetString("USR001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Des&amp;bloquear.
        /// </summary>
        internal static string USR001_Btn002 {
            get {
                return ResourceManager.GetString("USR001_Btn002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con&amp;traseña.
        /// </summary>
        internal static string USR001_Btn003 {
            get {
                return ResourceManager.GetString("USR001_Btn003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos de bloqueo.
        /// </summary>
        internal static string USR001_DgrUsr_cAttemptsBlock {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cAttemptsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos de acceso erroneos al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cAttemptsBlock_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cAttemptsBlock_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string USR001_DgrUsr_cClieName {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cClieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres y apellido del cliente.
        /// </summary>
        internal static string USR001_DgrUsr_cClieName_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cClieName_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        internal static string USR001_DgrUsr_cIs_Blocked {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cIs_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica si el usuario se encuentra bloqueado.
        /// </summary>
        internal static string USR001_DgrUsr_cIs_Blocked_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cIs_Blocked_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string USR001_DgrUsr_cLanguage {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma asociado al usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cLanguage_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cLanguage_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        internal static string USR001_DgrUsr_cNik {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias de usuario para ingreso al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cNik_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cNik_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string USR001_DgrUsr_cPassword {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña de usuario para ingreso al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cPassword_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cPassword_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cUser {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cUser_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cUser_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Usuario.
        /// </summary>
        internal static string USR001_Grp01 {
            get {
                return ResourceManager.GetString("USR001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string USR001_Title {
            get {
                return ResourceManager.GetString("USR001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar algún usuario.
        /// </summary>
        internal static string USR001_Val001 {
            get {
                return ResourceManager.GetString("USR001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario seleccionado no se encuentra bloqueado.
        /// </summary>
        internal static string USR001_Val002 {
            get {
                return ResourceManager.GetString("USR001_Val002", resourceCulture);
            }
        }
    }
}
