//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSecurity.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSecurity.Languages.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Depurar.
        /// </summary>
        internal static string BIT001_Btn001 {
            get {
                return ResourceManager.GetString("BIT001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Imprimir.
        /// </summary>
        internal static string BIT001_Btn002 {
            get {
                return ResourceManager.GetString("BIT001_Btn002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string BIT001_DgrBit_cCriticality {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cCriticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de criticidad del proceso registrado en la bitacora.
        /// </summary>
        internal static string BIT001_DgrBit_cCriticality_tt {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cCriticality_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string BIT001_DgrBit_cEffectDate {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cEffectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha en la que se registro el movimiento en la bitacora.
        /// </summary>
        internal static string BIT001_DgrBit_cEffectDate_tt {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cEffectDate_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador.
        /// </summary>
        internal static string BIT001_DgrBit_cLog {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código incremental de la bitacora.
        /// </summary>
        internal static string BIT001_DgrBit_cLog_tt {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cLog_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string BIT001_DgrBit_cNik {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario asociado al registro de la bitacora.
        /// </summary>
        internal static string BIT001_DgrBit_cNik_tt {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cNik_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T. Movimiento.
        /// </summary>
        internal static string BIT001_DgrBit_cTypMovement {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cTypMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de movimiento asociado a la bitacora.
        /// </summary>
        internal static string BIT001_DgrBit_cTypMovement_tt {
            get {
                return ResourceManager.GetString("BIT001_DgrBit_cTypMovement_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda.
        /// </summary>
        internal static string BIT001_Grp01 {
            get {
                return ResourceManager.GetString("BIT001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma la depuración de la Bitacora?.
        /// </summary>
        internal static string BIT001_Msg001 {
            get {
                return ResourceManager.GetString("BIT001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Bitacora.
        /// </summary>
        internal static string BIT001_Title {
            get {
                return ResourceManager.GetString("BIT001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Bitácora.
        /// </summary>
        internal static string BITR001_Title {
            get {
                return ResourceManager.GetString("BITR001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string BKP001_Grp01 {
            get {
                return ResourceManager.GetString("BKP001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Archivos.
        /// </summary>
        internal static string BKP001_LblFiles {
            get {
                return ResourceManager.GetString("BKP001_LblFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de requerir un respaldo multivolumen debe seleccionar la cantidad de archivos a crear.
        /// </summary>
        internal static string BKP001_LblText {
            get {
                return ResourceManager.GetString("BKP001_LblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El backup se realizó correctamente.
        /// </summary>
        internal static string BKP001_Msg001 {
            get {
                return ResourceManager.GetString("BKP001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backups.
        /// </summary>
        internal static string BKP001_Title {
            get {
                return ResourceManager.GetString("BKP001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar una ruta para realizar el backup.
        /// </summary>
        internal static string BKP001_Val001 {
            get {
                return ResourceManager.GetString("BKP001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El recalcúlo de DV finalizó correctamente.
        /// </summary>
        internal static string DVI_Msg001 {
            get {
                return ResourceManager.GetString("DVI_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo errores recalculando los DV.
        /// </summary>
        internal static string DVI_Msg002 {
            get {
                return ResourceManager.GetString("DVI_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Recalcular.
        /// </summary>
        internal static string DVI001_Btn001 {
            get {
                return ResourceManager.GetString("DVI001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        internal static string DVI001_DgrDVI_cId {
            get {
                return ResourceManager.GetString("DVI001_DgrDVI_cId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número secuencial.
        /// </summary>
        internal static string DVI001_DgrDVI_cId_tt {
            get {
                return ResourceManager.GetString("DVI001_DgrDVI_cId_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        internal static string DVI001_DgrDVI_cTable {
            get {
                return ResourceManager.GetString("DVI001_DgrDVI_cTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla cuya integridad fue violada.
        /// </summary>
        internal static string DVI001_DgrDVI_cTable_tt {
            get {
                return ResourceManager.GetString("DVI001_DgrDVI_cTable_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablas afectadas.
        /// </summary>
        internal static string DVI001_Grp01 {
            get {
                return ResourceManager.GetString("DVI001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recálcular DV.
        /// </summary>
        internal static string DVI001_Title {
            get {
                return ResourceManager.GetString("DVI001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string FAM001_DgrFam_cDescript {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción larga.
        /// </summary>
        internal static string FAM001_DgrFam_cDescript_tt {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cDescript_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        internal static string FAM001_DgrFam_cFamily {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de familia.
        /// </summary>
        internal static string FAM001_DgrFam_cFamily_tt {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cFamily_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Corta.
        /// </summary>
        internal static string FAM001_DgrFam_cShort_Desc {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cShort_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción corta.
        /// </summary>
        internal static string FAM001_DgrFam_cShort_Desc_tt {
            get {
                return ResourceManager.GetString("FAM001_DgrFam_cShort_Desc_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        internal static string FAM001_Grp02 {
            get {
                return ResourceManager.GetString("FAM001_Grp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string FAM001_Lbl001 {
            get {
                return ResourceManager.GetString("FAM001_Lbl001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Corta:.
        /// </summary>
        internal static string FAM001_Lbl002 {
            get {
                return ResourceManager.GetString("FAM001_Lbl002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la familia seleccionada?.
        /// </summary>
        internal static string FAM001_Msg001 {
            get {
                return ResourceManager.GetString("FAM001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error la familia tiene patentes y/o usuarios vinculados.
        /// </summary>
        internal static string FAM001_Msg002 {
            get {
                return ResourceManager.GetString("FAM001_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string FAM001_Title {
            get {
                return ResourceManager.GetString("FAM001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción larga debe estar completa.
        /// </summary>
        internal static string FAM001_Val001 {
            get {
                return ResourceManager.GetString("FAM001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción corta debe estar completa.
        /// </summary>
        internal static string FAM001_Val002 {
            get {
                return ResourceManager.GetString("FAM001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Agregado.
        /// </summary>
        internal static string GEN001_Btn001 {
            get {
                return ResourceManager.GetString("GEN001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Modificado.
        /// </summary>
        internal static string GEN001_Btn002 {
            get {
                return ResourceManager.GetString("GEN001_Btn002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Eliminado.
        /// </summary>
        internal static string GEN001_Btn003 {
            get {
                return ResourceManager.GetString("GEN001_Btn003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cerrar.
        /// </summary>
        internal static string GEN001_Btn004 {
            get {
                return ResourceManager.GetString("GEN001_Btn004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Buscar.
        /// </summary>
        internal static string GEN001_Btn005 {
            get {
                return ResourceManager.GetString("GEN001_Btn005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        internal static string GEN001_Btn006 {
            get {
                return ResourceManager.GetString("GEN001_Btn006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ca&amp;ncelar.
        /// </summary>
        internal static string GEN001_Btn007 {
            get {
                return ResourceManager.GetString("GEN001_Btn007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancela los cambios solicitados.
        /// </summary>
        internal static string GEN001_Btn007_tt {
            get {
                return ResourceManager.GetString("GEN001_Btn007_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Obtener.
        /// </summary>
        internal static string GEN001_Btn008 {
            get {
                return ResourceManager.GetString("GEN001_Btn008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Limpiar.
        /// </summary>
        internal static string GEN001_Btn009 {
            get {
                return ResourceManager.GetString("GEN001_Btn009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Guardar.
        /// </summary>
        internal static string GEN001_Btn010 {
            get {
                return ResourceManager.GetString("GEN001_Btn010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma los cambios solicitados.
        /// </summary>
        internal static string GEN001_Btn010_tt {
            get {
                return ResourceManager.GetString("GEN001_Btn010_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A&amp;gregar.
        /// </summary>
        internal static string GEN001_Btn011 {
            get {
                return ResourceManager.GetString("GEN001_Btn011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Seleccionar.
        /// </summary>
        internal static string GEN001_Btn012 {
            get {
                return ResourceManager.GetString("GEN001_Btn012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con&amp;firmar.
        /// </summary>
        internal static string GEN001_Btn013 {
            get {
                return ResourceManager.GetString("GEN001_Btn013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Imprimir.
        /// </summary>
        internal static string GEN001_Btn014 {
            get {
                return ResourceManager.GetString("GEN001_Btn014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea confirmar los cambios realizados?.
        /// </summary>
        internal static string GEN001_Msg001 {
            get {
                return ResourceManager.GetString("GEN001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario seleccionado no existe.
        /// </summary>
        internal static string GEN001_Msg002 {
            get {
                return ResourceManager.GetString("GEN001_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un cliente válido.
        /// </summary>
        internal static string GEN001_Msg003 {
            get {
                return ResourceManager.GetString("GEN001_Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es obligatorio.
        /// </summary>
        internal static string GEN001_Val001 {
            get {
                return ResourceManager.GetString("GEN001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ingresado no es numérico.
        /// </summary>
        internal static string GEN001_Val002 {
            get {
                return ResourceManager.GetString("GEN001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cancelar.
        /// </summary>
        internal static string Login_BtnCancel {
            get {
                return ResourceManager.GetString("Login_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        internal static string Login_BtnOk {
            get {
                return ResourceManager.GetString("Login_BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string Login_LblPass {
            get {
                return ResourceManager.GetString("Login_LblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario:.
        /// </summary>
        internal static string Login_LblUser {
            get {
                return ResourceManager.GetString("Login_LblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña inválidos.
        /// </summary>
        internal static string Login_Msg001 {
            get {
                return ResourceManager.GetString("Login_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe completar los campos usuario y contraseña.
        /// </summary>
        internal static string Login_Msg002 {
            get {
                return ResourceManager.GetString("Login_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra bloqueado, contacte al administrador del sistema.
        /// </summary>
        internal static string Login_Msg003 {
            get {
                return ResourceManager.GetString("Login_Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos: {0}, luego de 3 intentos el usuario será bloqueado.
        /// </summary>
        internal static string Login_Msg004 {
            get {
                return ResourceManager.GetString("Login_Msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Principal &quot;Gabe&quot;.
        /// </summary>
        internal static string MDI_Gabe {
            get {
                return ResourceManager.GetString("MDI_Gabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        internal static string MDI_Gabe_Mnu001 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        internal static string MDI_Gabe_Mnu002 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string MDI_Gabe_Mnu003 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string MDI_Gabe_Mnu005 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string MDI_Gabe_Mnu007 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Familia.
        /// </summary>
        internal static string MDI_Gabe_Mnu008 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Patente.
        /// </summary>
        internal static string MDI_Gabe_Mnu009 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Bitacora.
        /// </summary>
        internal static string MDI_Gabe_Mnu010 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string MDI_Gabe_Mnu013 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes.
        /// </summary>
        internal static string MDI_Gabe_Mnu014 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup&apos;s.
        /// </summary>
        internal static string MDI_Gabe_Mnu015 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore&apos;s.
        /// </summary>
        internal static string MDI_Gabe_Mnu016 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recálcular DV.
        /// </summary>
        internal static string MDI_Gabe_Mnu022 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia Patente.
        /// </summary>
        internal static string MDI_Gabe_Mnu023 {
            get {
                return ResourceManager.GetString("MDI_Gabe_Mnu023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string PAT001_DgrPat_cDescript {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción larga.
        /// </summary>
        internal static string PAT001_DgrPat_cDescript_tt {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cDescript_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        internal static string PAT001_DgrPat_cPatent {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de patente.
        /// </summary>
        internal static string PAT001_DgrPat_cPatent_tt {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cPatent_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Corta.
        /// </summary>
        internal static string PAT001_DgrPat_cShort_Desc {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cShort_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción corta.
        /// </summary>
        internal static string PAT001_DgrPat_cShort_Desc_tt {
            get {
                return ResourceManager.GetString("PAT001_DgrPat_cShort_Desc_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        internal static string PAT001_Grp02 {
            get {
                return ResourceManager.GetString("PAT001_Grp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string PAT001_Lbl001 {
            get {
                return ResourceManager.GetString("PAT001_Lbl001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Corta:.
        /// </summary>
        internal static string PAT001_Lbl002 {
            get {
                return ResourceManager.GetString("PAT001_Lbl002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la patente seleccionada?.
        /// </summary>
        internal static string PAT001_Msg001 {
            get {
                return ResourceManager.GetString("PAT001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes.
        /// </summary>
        internal static string PAT001_Title {
            get {
                return ResourceManager.GetString("PAT001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción larga debe estar completa.
        /// </summary>
        internal static string PAT001_Val001 {
            get {
                return ResourceManager.GetString("PAT001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción corta debe estar completa.
        /// </summary>
        internal static string PAT001_Val002 {
            get {
                return ResourceManager.GetString("PAT001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string REC001_DgrOrd_cAmount {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad asociada al articulo.
        /// </summary>
        internal static string REC001_DgrOrd_cAmount_tt {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cAmount_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item.
        /// </summary>
        internal static string REC001_DgrOrd_cItem {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número consecutivo indicador de línea.
        /// </summary>
        internal static string REC001_DgrOrd_cItem_tt {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cItem_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        internal static string REC001_DgrOrd_cPrice {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio asociado al articulo.
        /// </summary>
        internal static string REC001_DgrOrd_cPrice_tt {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cPrice_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string REC001_DgrOrd_cProducto {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de producto asocado al articulo.
        /// </summary>
        internal static string REC001_DgrOrd_cProducto_tt {
            get {
                return ResourceManager.GetString("REC001_DgrOrd_cProducto_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remito.
        /// </summary>
        internal static string REC001_Grp03 {
            get {
                return ResourceManager.GetString("REC001_Grp03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de Pago:.
        /// </summary>
        internal static string REC001_LblMod_Pay {
            get {
                return ResourceManager.GetString("REC001_LblMod_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación:.
        /// </summary>
        internal static string REC001_LblObserv {
            get {
                return ResourceManager.GetString("REC001_LblObserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido:.
        /// </summary>
        internal static string REC001_LblOrder {
            get {
                return ResourceManager.GetString("REC001_LblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total:.
        /// </summary>
        internal static string REC001_LblTotal {
            get {
                return ResourceManager.GetString("REC001_LblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub Total:.
        /// </summary>
        internal static string REC001_LblTotSub {
            get {
                return ResourceManager.GetString("REC001_LblTotSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Pedido ingresado no existe.
        /// </summary>
        internal static string REC001_Msg001 {
            get {
                return ResourceManager.GetString("REC001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se generó el Remito N°.
        /// </summary>
        internal static string REC001_Msg002 {
            get {
                return ResourceManager.GetString("REC001_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta Remito.
        /// </summary>
        internal static string REC001_Title {
            get {
                return ResourceManager.GetString("REC001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Forma de Pago es obligatorio.
        /// </summary>
        internal static string REC001_Val001 {
            get {
                return ResourceManager.GetString("REC001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Observación es obligatorio.
        /// </summary>
        internal static string REC001_Val002 {
            get {
                return ResourceManager.GetString("REC001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string REC002_DgrRec_cClient {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de cliente.
        /// </summary>
        internal static string REC002_DgrRec_cClient_tt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cClient_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Pago.
        /// </summary>
        internal static string REC002_DgrRec_cModPay {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cModPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de pago.
        /// </summary>
        internal static string REC002_DgrRec_cModPay_tt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cModPay_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remito.
        /// </summary>
        internal static string REC002_DgrRec_cReceipt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de remito.
        /// </summary>
        internal static string REC002_DgrRec_cReceipt_tt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cReceipt_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string REC002_DgrRec_cReceiptDate {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha del remito.
        /// </summary>
        internal static string REC002_DgrRec_cReceiptDate_tt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cReceiptDate_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string REC002_DgrRec_cTotal {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe total del remito.
        /// </summary>
        internal static string REC002_DgrRec_cTotal_tt {
            get {
                return ResourceManager.GetString("REC002_DgrRec_cTotal_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitos.
        /// </summary>
        internal static string REC002_Grp01 {
            get {
                return ResourceManager.GetString("REC002_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresión Remito.
        /// </summary>
        internal static string REC002_Title {
            get {
                return ResourceManager.GetString("REC002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir Remito.
        /// </summary>
        internal static string RECR001_Title {
            get {
                return ResourceManager.GetString("RECR001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string RST001_Grp01 {
            get {
                return ResourceManager.GetString("RST001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Archivos.
        /// </summary>
        internal static string RST001_LblFiles {
            get {
                return ResourceManager.GetString("RST001_LblFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de requerir la restauración de un respaldo multivolumen debe seleccionar la cantidad de archivos a restaurar.
        /// </summary>
        internal static string RST001_LblText {
            get {
                return ResourceManager.GetString("RST001_LblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La restauración se realizó correctamente, el sistema se cerrará.
        /// </summary>
        internal static string RST001_Msg001 {
            get {
                return ResourceManager.GetString("RST001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore&apos;s.
        /// </summary>
        internal static string RST001_Title {
            get {
                return ResourceManager.GetString("RST001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar una ruta para realizar la restauración.
        /// </summary>
        internal static string RST001_Val001 {
            get {
                return ResourceManager.GetString("RST001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cerrar.
        /// </summary>
        internal static string Splash_BtnCancel {
            get {
                return ResourceManager.GetString("Splash_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicializando....
        /// </summary>
        internal static string Splash001_Msg000 {
            get {
                return ResourceManager.GetString("Splash001_Msg000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando actualizaciones....
        /// </summary>
        internal static string Splash001_Msg001 {
            get {
                return ResourceManager.GetString("Splash001_Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectandose a la base de datos....
        /// </summary>
        internal static string Splash001_Msg002 {
            get {
                return ResourceManager.GetString("Splash001_Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificando integridad del sistema....
        /// </summary>
        internal static string Splash001_Msg003 {
            get {
                return ResourceManager.GetString("Splash001_Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando aplicación....
        /// </summary>
        internal static string Splash001_Msg004 {
            get {
                return ResourceManager.GetString("Splash001_Msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Verificación de integridad, consulte al Administrador del Sistema.
        /// </summary>
        internal static string Splash001_MsgBox001 {
            get {
                return ResourceManager.GetString("Splash001_MsgBox001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sistema ya se encuentra abierto.
        /// </summary>
        internal static string Splash001_MsgBox002 {
            get {
                return ResourceManager.GetString("Splash001_MsgBox002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mod. &amp;Idioma.
        /// </summary>
        internal static string USR001_Btn001 {
            get {
                return ResourceManager.GetString("USR001_Btn001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Des&amp;bloquear.
        /// </summary>
        internal static string USR001_Btn002 {
            get {
                return ResourceManager.GetString("USR001_Btn002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con&amp;traseña.
        /// </summary>
        internal static string USR001_Btn003 {
            get {
                return ResourceManager.GetString("USR001_Btn003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos de bloqueo.
        /// </summary>
        internal static string USR001_DgrUsr_cAttemptsBlock {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cAttemptsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos de acceso erroneos al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cAttemptsBlock_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cAttemptsBlock_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string USR001_DgrUsr_cClieName {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cClieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres y apellido del cliente.
        /// </summary>
        internal static string USR001_DgrUsr_cClieName_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cClieName_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        internal static string USR001_DgrUsr_cIs_Blocked {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cIs_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica si el usuario se encuentra bloqueado.
        /// </summary>
        internal static string USR001_DgrUsr_cIs_Blocked_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cIs_Blocked_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string USR001_DgrUsr_cLanguage {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma asociado al usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cLanguage_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cLanguage_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        internal static string USR001_DgrUsr_cNik {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias de usuario para ingreso al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cNik_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cNik_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string USR001_DgrUsr_cPassword {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña de usuario para ingreso al sistema.
        /// </summary>
        internal static string USR001_DgrUsr_cPassword_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cPassword_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cUser {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Usuario.
        /// </summary>
        internal static string USR001_DgrUsr_cUser_tt {
            get {
                return ResourceManager.GetString("USR001_DgrUsr_cUser_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Usuario.
        /// </summary>
        internal static string USR001_Grp01 {
            get {
                return ResourceManager.GetString("USR001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string USR001_Title {
            get {
                return ResourceManager.GetString("USR001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar algún usuario.
        /// </summary>
        internal static string USR001_Val001 {
            get {
                return ResourceManager.GetString("USR001_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario seleccionado no se encuentra bloqueado.
        /// </summary>
        internal static string USR001_Val002 {
            get {
                return ResourceManager.GetString("USR001_Val002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        internal static string USR002_ChkAdmin {
            get {
                return ResourceManager.GetString("USR002_ChkAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloqueado.
        /// </summary>
        internal static string USR002_ChkBloqued {
            get {
                return ResourceManager.GetString("USR002_ChkBloqued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregado Usuario.
        /// </summary>
        internal static string USR002_Grp01 {
            get {
                return ResourceManager.GetString("USR002_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado Usuario.
        /// </summary>
        internal static string USR002_Grp02 {
            get {
                return ResourceManager.GetString("USR002_Grp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado Usuario.
        /// </summary>
        internal static string USR002_Grp03 {
            get {
                return ResourceManager.GetString("USR002_Grp03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Usuario.
        /// </summary>
        internal static string USR002_Grp04 {
            get {
                return ResourceManager.GetString("USR002_Grp04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado Idioma.
        /// </summary>
        internal static string USR002_Grp05 {
            get {
                return ResourceManager.GetString("USR002_Grp05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        internal static string USR002_Grp06 {
            get {
                return ResourceManager.GetString("USR002_Grp06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias:.
        /// </summary>
        internal static string USR002_lbl001 {
            get {
                return ResourceManager.GetString("USR002_lbl001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string USR002_lbl002 {
            get {
                return ResourceManager.GetString("USR002_lbl002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos de Bloqueo:.
        /// </summary>
        internal static string USR002_lbl003 {
            get {
                return ResourceManager.GetString("USR002_lbl003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje:.
        /// </summary>
        internal static string USR002_lbl004 {
            get {
                return ResourceManager.GetString("USR002_lbl004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string USR002_Title {
            get {
                return ResourceManager.GetString("USR002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea confirmar la eliminación del usuario?.
        /// </summary>
        internal static string USR002_Val004 {
            get {
                return ResourceManager.GetString("USR002_Val004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blanquear Contraseña.
        /// </summary>
        internal static string USR003_Grp01 {
            get {
                return ResourceManager.GetString("USR003_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias:.
        /// </summary>
        internal static string USR003_lbl001 {
            get {
                return ResourceManager.GetString("USR003_lbl001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña:.
        /// </summary>
        internal static string USR003_lbl002 {
            get {
                return ResourceManager.GetString("USR003_lbl002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar:.
        /// </summary>
        internal static string USR003_lbl003 {
            get {
                return ResourceManager.GetString("USR003_lbl003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña Usuario.
        /// </summary>
        internal static string USR003_Title {
            get {
                return ResourceManager.GetString("USR003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La confirmación de la contraseña no coincide.
        /// </summary>
        internal static string USR003_Val001 {
            get {
                return ResourceManager.GetString("USR003_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionado.
        /// </summary>
        internal static string USR004_DgrFam_cChecked {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica que la familia se encuentra agregada o no.
        /// </summary>
        internal static string USR004_DgrFam_cChecked_tt {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cChecked_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        internal static string USR004_DgrFam_cCodFamily {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cCodFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de familia.
        /// </summary>
        internal static string USR004_DgrFam_cCodFamily_tt {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cCodFamily_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string USR004_DgrFam_cFamily {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la familia.
        /// </summary>
        internal static string USR004_DgrFam_cFamily_tt {
            get {
                return ResourceManager.GetString("USR004_DgrFam_cFamily_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Usuario.
        /// </summary>
        internal static string USR004_Grp01 {
            get {
                return ResourceManager.GetString("USR004_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Familia.
        /// </summary>
        internal static string USR004_Title {
            get {
                return ResourceManager.GetString("USR004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe elegir algun usuario.
        /// </summary>
        internal static string USR004_Val001 {
            get {
                return ResourceManager.GetString("USR004_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionado.
        /// </summary>
        internal static string USR005_DgrPat_cChecked {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica que la patente se encuentra agregada o no.
        /// </summary>
        internal static string USR005_DgrPat_cChecked_tt {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cChecked_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        internal static string USR005_DgrPat_cCodPatent {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cCodPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de patente.
        /// </summary>
        internal static string USR005_DgrPat_cCodPatent_tt {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cCodPatent_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia.
        /// </summary>
        internal static string USR005_DgrPat_cFamily {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador que la patente proviene de una familia.
        /// </summary>
        internal static string USR005_DgrPat_cFamily_tt {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cFamily_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        internal static string USR005_DgrPat_cIsDeny {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cIsDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indica si la patente se encuentra denegando.
        /// </summary>
        internal static string USR005_DgrPat_cIsDeny_tt {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cIsDeny_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string USR005_DgrPat_cPatent {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la patente.
        /// </summary>
        internal static string USR005_DgrPat_cPatent_tt {
            get {
                return ResourceManager.GetString("USR005_DgrPat_cPatent_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string USR005_Grp01 {
            get {
                return ResourceManager.GetString("USR005_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Patente.
        /// </summary>
        internal static string USR005_Title {
            get {
                return ResourceManager.GetString("USR005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe elegir algun usuario.
        /// </summary>
        internal static string USR005_Val001 {
            get {
                return ResourceManager.GetString("USR005_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe.
        /// </summary>
        internal static string USRCTRL01_Val001 {
            get {
                return ResourceManager.GetString("USRCTRL01_Val001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo usuario es obligatorio.
        /// </summary>
        internal static string USRCTRL01_Val003 {
            get {
                return ResourceManager.GetString("USRCTRL01_Val003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string USRL001_Grp01 {
            get {
                return ResourceManager.GetString("USRL001_Grp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Rápida Usuarios.
        /// </summary>
        internal static string USRL001_Title {
            get {
                return ResourceManager.GetString("USRL001_Title", resourceCulture);
            }
        }
    }
}
